# Generated by Django 2.2 on 2020-08-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alumno_persona_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('fechaSalida', models.DateField(auto_now=True)),
                ('fechaRegreso', models.DateField()),
            ],
        ),
    ]
