# Generated by Django 2.2 on 2020-08-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipoPersona',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Persona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaSalida',
            field=models.DateField(),
        ),
    ]
