# Generated by Django 2.2 on 2020-08-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20200814_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='tipoMaterial',
        ),
    ]
