# Generated by Django 2.2 on 2020-08-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_remove_material_tipomaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='Material',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Persona',
            new_name='persona',
        ),
    ]
